/*
#define  ARMOR_BALLISTIC_BB			5
#define  ARMOR_BALLISTIC_MICRO		10
#define  ARMOR_BALLISTIC_COMPACT	15
#define  ARMOR_BALLISTIC_PISTOL		25
#define  ARMOR_BALLISTIC_SHOTGUN	40
#define  ARMOR_BALLISTIC_PDW		45
#define  ARMOR_BALLISTIC_CARBINE	55
#define  ARMOR_BALLISTIC_RIFLE		65
#define  ARMOR_BALLISTIC_AP			85
#define  ARMOR_BALLISTIC_HEAVY		100

#define  ARMOR_LASER_POINTER		5
#define  ARMOR_LASER_MICRO			10
#define  ARMOR_LASER_SMALL			20
#define  ARMOR_LASER_HANDGUNS		30
#define  ARMOR_LASER_MAJOR			40
#define  ARMOR_LASER_RIFLES			50
#define  ARMOR_LASER_HEAVY			75
#define  ARMOR_LASER_PROOF			90

#define  ARMOR_SLASH_SCRATCHES		5
#define  ARMOR_SLASH_KNIVES			15
#define  ARMOR_SLASH_DAGGERS		20
#define  ARMOR_SLASH_SWORDS			35
#define  ARMOR_SLASH_CHAINSAW		50
#define  ARMOR_SLASH_LIGHTSABRE		75

#define ARMOR_BLUNT_WIND			5
#define ARMOR_BLUNT_FISTCUFFS		15
#define ARMOR_BLUNT_BASEBALL		30
#define ARMOR_BLUNT_TOOLS			45
#define ARMOR_BLUNT_HAMMER			60
#define ARMOR_BLUNT_SLEDGEHAMMER	75
*/

#define CLASS1_PUNCTURE		5
#define CLASS2_PUNCTURE		20
#define CLASS3_PUNCTURE		35
#define CLASS4_PUNCTURE		50
#define CLASS5_PUNCTURE		60
#define CLASS6_PUNCTURE		75
#define CLASS7_PUNCTURE		90
#define CLASS8_PUNCTURE		100

#define CLASS1_SLASH		15
#define CLASS2_SLASH		25
#define CLASS3_SLASH		40
#define CLASS4_SLASH		55
#define CLASS5_SLASH		70
#define CLASS6_SLASH		80
#define CLASS7_SLASH		90
#define CLASS8_SLASH		100

#define CLASS1_BLUNT		10
#define CLASS2_BLUNT		25
#define CLASS3_BLUNT		35
#define CLASS4_BLUNT		50
#define CLASS5_BLUNT		60
#define CLASS6_BLUNT		75
#define CLASS7_BLUNT		90
#define CLASS8_BLUNT		100

#define CLASS1_LASER		5
#define CLASS2_LASER		15
#define CLASS3_LASER		25
#define CLASS4_LASER		40
#define CLASS5_LASER		50
#define CLASS6_LASER		75
#define CLASS7_LASER		90
#define CLASS8_LASER		100

/*

// Ordinary clothing with some defensive value

#define BODYARMOR_THIN_CLOTHES list(BLUNT = ARMOR_MELEE_SCRATCHES, PUNCTURE = ARMOR_BALLISTIC_BB, SLASH = ARMOR_MELEE_SCRATCHES, LASER = ARMOR_LASER_POINTER, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_THICK_CLOTHES list(BLUNT = ARMOR_MELEE_SMALL, PUNCTURE = 5, SLASH = ARMOR_MELEE_SMALL, LASER = ARMOR_LASER_MICRO, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_HEAVY_CLOTHES list(BLUNT = ARMOR_MELEE_KNIVES, PUNCTURE = 5, SLASH = ARMOR_MELEE_KNIVES, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)

// Armor from wasteland materials such as leather, scrap, animal hides, etc (Wastelanders, Raiders)

#define BODYARMOR_SCRAP_MINIMAL list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_BB, SLASH = ARMOR_MELEE_DAGGERS, LASER = ARMOR_LASER_MICRO, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_SCRAP_DECENT list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_MICRO, SLASH = ARMOR_MELEE_RESISTANT, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_SCRAP_HEAVY list(BLUNT = ARMOR_MELEE_MAJOR, PUNCTURE = ARMOR_BALLISTIC_PISTOL, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 15, BIO = 0, FIRE = 0, ACID = 0)

#define BODYARMOR_HIDES_MINIMAL list(BLUNT = ARMOR_MELEE_SMALL, PUNCTURE = ARMOR_BALLISTIC_BB, SLASH = ARMOR_MELEE_KNIVES, LASER = ARMOR_LASER_MICRO, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_HIDES_DECENT list(BLUNT = ARMOR_MELEE_DAGGERS, PUNCTURE = ARMOR_BALLISTIC_BB, SLASH = ARMOR_MELEE_RESISTANT, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_HIDES_HEAVY list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_MICRO, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_HANDGUNS, ENERGY = 0, BOMB = 15, BIO = 0, FIRE = 0, ACID = 0)

// Pre-war and current-era armor made out of advanced materials (Enclave, BoS)

#define BODYARMOR_MILITARY_MEDIUM list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_SHOTGUN, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_HANDGUNS, ENERGY = 15, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_MILITARY_HEAVY list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_RIFLE, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_MAJOR, ENERGY = 30, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_MILITARY_ELITEHEAVY list(BLUNT = ARMOR_MELEE_VERY_HIGH, PUNCTURE = ARMOR_BALLISTIC_AP, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_RIFLES, ENERGY = 30, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)

// Steel ballistic armor (Anyone)

#define BODYARMOR_STEEL_MEDIUM list(BLUNT = ARMOR_MELEE_MAJOR, PUNCTURE = ARMOR_BALLISTIC_PISTOL, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_MICRO, ENERGY = 15, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_STEEL_HEAVY list(BLUNT = ARMOR_MELEE_MAJOR, PUNCTURE = ARMOR_BALLISTIC_PDW, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_SMALL, ENERGY = 20, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_STEEL_SALVAGED list(BLUNT = ARMOR_MELEE_FULLPLATE, PUNCTURE = ARMOR_BALLISTIC_CARBINE, SLASH = ARMOR_MELEE_SHIELDED, LASER = ARMOR_LASER_RIFLES, ENERGY = 25, BOMB = 25, BIO = 0, FIRE = 50, ACID = 75)
#define BODYARMOR_STEEL_POWERARMOR list(BLUNT = ARMOR_MELEE_FULLPLATE, PUNCTURE = ARMOR_BALLISTIC_RIFLE, SLASH = ARMOR_MELEE_SHIELDED, LASER = ARMOR_LASER_RIFLES, ENERGY = 25, BOMB = 25, BIO = 0, FIRE = 75, ACID = 100)

// Pre-war armor made out of soft materials (NCR)

#define BODYARMOR_KEVLAR_MINIMAL list(BLUNT = ARMOR_MELEE_SMALL, PUNCTURE = ARMOR_BALLISTIC_MICRO, SLASH = ARMOR_MELEE_KNIVES, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_KEVLAR_LIGHT list(BLUNT = ARMOR_MELEE_SMALL, PUNCTURE = ARMOR_BALLISTIC_COMPACT, SLASH = ARMOR_MELEE_DAGGERS, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_KEVLAR_MEDIUM list(BLUNT = ARMOR_MELEE_SMALL, PUNCTURE = ARMOR_BALLISTIC_PISTOL, SLASH = ARMOR_MELEE_RESISTANT, LASER = ARMOR_LASER_HANDGUNS, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_KEVLAR_RIGIDHEAVY list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_SHOTGUN, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_HANDGUNS, ENERGY = 0, BOMB = 0, BIO = 0, FIRE = 0, ACID = 0)

#define BODYARMOR_KEVLAR_HAZARD list(BLUNT = ARMOR_MELEE_SMALL, PUNCTURE = ARMOR_BALLISTIC_COMPACT, SLASH = ARMOR_MELEE_RESISTANT, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 0, BIO = 100, FIRE = 75, ACID = 100)

// Medieval-style steel plate armor with some ballistic reinforcement (Legion)

#define BODYARMOR_MEDIEVAL_MINIMAL list(BLUNT = ARMOR_MELEE_RESISTANT, PUNCTURE = ARMOR_BALLISTIC_MICRO, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_MICRO, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_MEDIEVAL_DECENT list(BLUNT = ARMOR_MELEE_MAJOR, PUNCTURE = ARMOR_BALLISTIC_COMPACT, SLASH = ARMOR_MELEE_MAJOR, LASER = ARMOR_LASER_MICRO, ENERGY = 0, BOMB = 5, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_MEDIEVAL_HEAVY list(BLUNT = ARMOR_MELEE_VERY_HIGH, PUNCTURE = ARMOR_BALLISTIC_PISTOL, SLASH = ARMOR_MELEE_VERY_HIGH, LASER = ARMOR_LASER_SMALL, ENERGY = 0, BOMB = 10, BIO = 0, FIRE = 0, ACID = 0)
#define BODYARMOR_MEDIEVAL_ROYALHEAVY list(BLUNT = ARMOR_MELEE_FULLPLATE, PUNCTURE = ARMOR_BALLISTIC_SHOTGUN, SLASH = ARMOR_MELEE_SHIELDED, LASER = ARMOR_LASER_HANDGUNS, ENERGY = 0, BOMB = 10, BIO = 0, FIRE = 0, ACID = 0)

*/